name: Build

on:
    push:
        branches:
            - main
        tags:
            - '**'
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: macos-14
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: '17'
                    cache: 'gradle'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3

            -   name: konan cache
                uses: actions/cache@v4
                with:
                    path: ~/.konan
                    key: ${{ runner.os }}-konan

            -   name: Check
                run: ./gradlew check

            -   name: Upload artifacts
                if: failure()
                uses: actions/upload-artifact@master
                with:
                    name: hs_err_pid.log
                    path: 'hs_err_**.log'

            -   name: Build
                run: ./gradlew build -x check -x lintVitalRelease

            -   name: Prepare tag properties
                if: startsWith(github.ref, 'refs/tags/')
                run: |
                    echo "${{secrets.GPG_SIGNING_SECRET_KEY_RING_FILE_BASE64}}" > $HOME/.gradle/sonatype-appmattus-keys.gpg.b64
                    base64 -d -i $HOME/.gradle/sonatype-appmattus-keys.gpg.b64 -o $HOME/.gradle/sonatype-appmattus-keys.gpg
                    echo "${{secrets.GPG_GRADLE_PROPERTIES}}" > $HOME/.gradle/gradle.properties

            -   name: Upload tag
                if: startsWith(github.ref, 'refs/tags/')
                run: ./gradlew publishAllPublicationsToMavenCentral -P"signing.secretKeyRingFile=$(echo $HOME/.gradle/sonatype-appmattus-keys.gpg)"
