name: Build

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: gradle/wrapper-validation-action@v1

  build:
    needs: [validation]
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ macOS-latest, ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check
        run: ./gradlew check

      - name: Build
        run: ./gradlew build -x check -x lintVitalRelease

      - name: Prepare tag properties
        run: |
          echo "${{secrets.GPG_SIGNING_SECRET_KEY_RING_FILE_BASE64}}" > ~/.gradle/sonatype-appmattus-keys.gpg.b64
          base64 -d ~/.gradle/sonatype-appmattus-keys.gpg.b64 > ~/.gradle/sonatype-appmattus-keys.gpg
          echo "${{secrets.GPG_GRADLE_PROPERTIES}}" > ~/.gradle/gradle.properties
        if: startsWith(github.ref, 'refs/tags/')

      - name: Upload tag
        run: ./gradlew publish --no-daemon --no-parallel -Psigning.secretKeyRingFile=$(echo ~/.gradle/sonatype-appmattus-keys.gpg)
        if: startsWith(github.ref, 'refs/tags/')

  close:
      needs: [build]
      runs-on: ubuntu-latest
      steps:
      - name: Close and release tag
        run: ./gradlew closeAndReleaseRepository
        if: startsWith(github.ref, 'refs/tags/')
