name: Build

on:
    push:
        branches:
            - main
        tags:
            - '**'
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: macos-11
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                with:
                    distribution: 'zulu'
                    java-version: '17'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3

            -   name: konan cache
                uses: actions/cache@v3
                with:
                    path: ~/.konan
                    key: ${{ runner.os }}-konan

            -   name: Check
                run: ./gradlew check

            -   name: Build
                run: ./gradlew build -x check -x lintVitalRelease

            -   name: Prepare tag properties (*nix)
                if: runner.os != 'Windows' && startsWith(github.ref, 'refs/tags/')
                run: |
                    echo "${{secrets.GPG_SIGNING_SECRET_KEY_RING_FILE_BASE64}}" > $HOME/.gradle/sonatype-appmattus-keys.gpg.b64
                    base64 -d $HOME/.gradle/sonatype-appmattus-keys.gpg.b64 > $HOME/.gradle/sonatype-appmattus-keys.gpg
                    echo "${{secrets.GPG_GRADLE_PROPERTIES}}" > $HOME/.gradle/gradle.properties

            -   name: Prepare tag properties (windows)
                if: runner.os == 'Windows' &&  startsWith(github.ref, 'refs/tags/')
                run: |
                    echo "${{secrets.GPG_SIGNING_SECRET_KEY_RING_FILE_BASE64}}" > $HOME/.gradle/sonatype-appmattus-keys.gpg.b64
                    certutil -decode $HOME/.gradle/sonatype-appmattus-keys.gpg.b64 $HOME/.gradle/sonatype-appmattus-keys.gpg
                    echo "${{secrets.GPG_GRADLE_PROPERTIES}}" > $HOME/.gradle/gradle.properties

            -   name: Upload tag
                if: startsWith(github.ref, 'refs/tags/')
                run: ./gradlew publishAllPublicationsToMavenCentral -P"signing.secretKeyRingFile=$(echo $HOME/.gradle/sonatype-appmattus-keys.gpg)"
